import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SINC Partners",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex w-[100dvw] max-w-[100dvw] items-center flex-col min-h-[100dvh] bg-[#F4F4F4] ">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
